top-think/think

- thinkphp/library/think/lang.php
> 加载语言定义批量加载修复

- thinkphp/library/think/template.php
> 修正extend不能解析完整模板路径的问题

- tests/framework/thinkphp/library/think/appTest.php
- travis.test
消除首页indexController产生的欢迎界面，并测试欢迎界面是否与期待的字符串相等
> 消除首页indexController产生的欢迎界面，并测试欢迎界面是否与期待的字符串相等

- thinkphp/library/traits/model/Auto.php
- thinkphp/library/traits/model/Relation.php
> 1.改进自动验证支持关联验证

- thinkphp/library/traits/model/Auto.php
回调参数0, 在单字段验证时应为对应字段的值, 多字段时才为数组。
> 修正验证单一字段时回调参数0也被转成数组的问题.

- thinkphp/convention.php
- thinkphp/library/think/Session.php
新增var_session_id配置,解决flash上传session跨域的问题
> 新增var_session_id配置,解决flash上传session跨域的问题

- thinkphp/library/think/Template.php
- thinkphp/library/think/template/TagLib.php
- thinkphp/library/think/template/taglib/Cx.php
> 修正标签直接使用表达式时字符串被多截取一位的bug

- thinkphp/library/think/App.php
- thinkphp/library/think/Model.php
- thinkphp/library/traits/model/Adv.php
[notic] [2] strpos(): Empty needle /thinkphp/library/think/Model.php 第 1274 行
[notic] [2048] Declaration of traits\model\Adv::_before_write() should be compatible with think\Model::_before_write(&$data)
BIND_MODULE 出现错误 #206
> 修复部分notice错误

- thinkphp/helper.php
- thinkphp/library/think/Input.php
- thinkphp/tests/thinkphp/library/think/inputTest.php
> Input类增加path、file、data方法，支持.语法取多维数组的值。

- composer.json
> composer.json code style

- thinkphp/library/think/App.php
- thinkphp/library/think/Config.php
- thinkphp/library/think/Controller.php
- thinkphp/library/think/Cookie.php
- thinkphp/library/think/Debug.php
- thinkphp/library/think/Error.php
- thinkphp/library/think/Hook.php
- thinkphp/library/think/Model.php
- thinkphp/library/think/Response.php
- thinkphp/library/think/Session.php
- thinkphp/library/think/Template.php
- thinkphp/library/think/Url.php
- thinkphp/library/think/View.php
- thinkphp/library/think/cache/driver/Db.php
- thinkphp/library/think/cache/driver/File.php
- thinkphp/library/think/cache/driver/Memcache.php
- thinkphp/library/think/cache/driver/Secache.php
- thinkphp/library/think/db/Driver.php
- thinkphp/library/think/db/driver/Oracle.php
- thinkphp/library/think/db/driver/Pgsql.php
- thinkphp/library/think/log/alarm/Email.php
- thinkphp/library/think/log/driver/Socket.php
- thinkphp/library/think/template/TagLib.php
- thinkphp/library/traits/controller/Jump.php
- thinkphp/library/traits/model/Adv.php
- thinkphp/library/traits/model/Auto.php
- thinkphp/tests/thinkphp/library/think/debugTest.php
- thinkphp/tests/thinkphp/library/think/responseTest.php
- thinkphp/tests/thinkphp/library/think/sessionTest.php
1）修改了一些注释的错误参数类型和返回类型
2）修改了一些无意义的变量名
3）本次 commit 没有逻辑上的变动
> 修改了一些注释的错误参数类型、返回类型和部分无意义的变量名

- thinkphp/library/think/Error.php
- thinkphp/library/think/exception/ErrorException.php
添加Error异常的ErrorContext参数，并打印ErrorContext到异常页面
> 添加Error异常的ErrorContext参数，并打印ErrorContext到异常页面

- thinkphp/library/think/cache/driver/File.php
增加删除本地文件缓存时优先判断是否存在，如果存在则进行unlink删除操作
> 删除不存在的File缓存时异常

- thinkphp/tests/thinkphp/library/think/buildTest.php
- thinkphp/tests/thinkphp/library/think/cache/driver/fileTest.php
> 添加File缓存驱动测试

- thinkphp/library/think/Error.php
- thinkphp/library/think/Model.php
基于\think\Exception 才使用 getHttpStatus 方法
> 基于\think\Exception 才使用 getHttpStatus 方法

- public/.htaccess
> Revert "Update .htaccess"

- thinkphp/library/think/template/taglib/Cx.php
> 在taglib中增加U函数的简写

- thinkphp/library/think/Template.php
- thinkphp/library/think/template/TagLib.php
- thinkphp/library/think/template/driver/File.php
- thinkphp/library/think/template/driver/Sae.php
- thinkphp/library/think/template/taglib/Cx.php
- thinkphp/tests/thinkphp/library/think/extend.html
- thinkphp/tests/thinkphp/library/think/extend2.html
- thinkphp/tests/thinkphp/library/think/template/taglib/cxTest.php
- thinkphp/tests/thinkphp/library/think/templateTest.php
模板包含文件记录及更新时间直接写入缓存的模板中；改进标签别名的处理方式，别名不再定义方法；
去除include标签传参自动生成变量的代码；cx类增加function方法，用来生成匿名函数，结合{~$函数名()}可用于递归的实现。
> 优代部分代码；block标签内可以使用{__block__}来引用所继承模板中相应block标签的内容；

- think
改进不需要切换到应用根目录下也可执行命令行脚本（指定think文件全路径即可）
> 框架引导文件改为绝对路径

- public/router.php
> fixed #691

- .gitignore
此系统下 .DS_Store 可能会造成安全隐患（https://zh.wikipedia.org/wiki/.DS_Store）
> 增加 Mac OS X系统下忽略此文件
